---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1586,"creation_ts":"2013-07-16 19:06:00 -0700","short_desc":"12[\"__proto__\"] should probably not be a TypeError","delta_ts":"2015-07-10 08:35:05 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 15: May 14, 2013 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"enhancement","everconfirmed":true,"reporter":{"uid":"lukeh","name":"Luke Hoban"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"cc":"erik.arvidsson","long_desc":[{"commentid":4539,"comment_count":0,"who":{"uid":"lukeh","name":"Luke Hoban"},"bug_when":"2013-07-16 19:06:37 -0700","thetext":"All current engines I could try return Number.prototype for:\n \n  12[\"__proto__\"]\n \nBut the new spec says this should be a TypeError.\n \n\nItâ€™s more consistent with the other members of Object.prototype to do an implicit ToObject here, and apparently matches existing implementations.  Is it intentional that the spec is treating this as a TypeError?"},{"commentid":4540,"comment_count":1,"who":{"uid":"lukeh","name":"Luke Hoban"},"bug_when":"2013-07-16 19:06:51 -0700","thetext":"Allen commented in mail:\n\n\nWell, it was intentional, but perhaps wrong. As you say, the  set accessor probably needs to do a ToObject.  The set accessor probably only needs to do a CheckObjectCoercible  followed by an immediate return if the type of this is not Object (the wrapper and hence it's modified [[Prototype]] isn't observable, so it doesn't actually need to be created).\n\nFile a bug, and I'll put the revised algorithms into the ticket."},{"commentid":4541,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-07-17 08:38:48 -0700","thetext":"fixed in rev17 editor's draft. \n\nHere are the revised definitions:\n\nB.2.2.1.1\tget Object.prototype.__proto__ \nThe value of the [[Get]] attribute is a built-in function that requires no arguments. It performs the following steps:\n\n1.\tLet O be the result of calling ToObject passing the this value as the argument.\n2.\tReturnIfAbrupt(O).\n3.\tReturn the result of calling the [[GetInheritance]] internal method of O.\n\nB.2.2.1.2\tset Object.prototype.__proto__ \nThe value of the [[Set]] attribute is a built-in function that takes an argument proto. It performs the following steps:\n\n1.\tLet O be CheckObjectCoercible(this value).\n2.\tReturnIfAbrupt(O).\n3.\tIf Type(proto) is neither Object or Null, then throw a TypeError exception.\n4.\tIf Type(O) is not Object, then return proto.\n5.\tLet status be the result of calling the [[SetInheritance]] internal method of O with argument proto.\n6.\tReturnIfAbrupt(status).\n7.\tIf status is false, then throw a TypeError exception.\n8.\tReturn proto."},{"commentid":4544,"comment_count":3,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-07-17 09:25:14 -0700","thetext":"I also updated Object.setPrototypeOf \n\n15.2.3.19\tObject.setPrototypeOf ( O, proto )\nWhen the setPrototypeOf function is called with arguments O and proto, the following steps are taken:\n\n1.\tLet O be CheckObjectCoercible(O).\n2.\tReturnIfAbrupt(O).\n3.\tIf Type(proto) is neither Object or Null, then throw a TypeError exception.\n4.\tIf Type(O) is not Object, then return O.\n5.\tLet status be the result of calling the [[SetInheritance]] internal method of O with argument proto.\n6.\tReturnIfAbrupt(status).\n7.\tIf status is false, then throw a TypeError exception.\n8.\tReturn O."},{"commentid":4566,"comment_count":4,"who":{"uid":"lukeh","name":"Luke Hoban"},"bug_when":"2013-07-24 10:20:37 -0700","thetext":"Are we sure that Object.setPrototypeOf should do ToObject?  None of the other Object.* methods do this."},{"commentid":5180,"comment_count":5,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-08-23 08:23:32 -0700","thetext":"fixed in rev17, August 23, 2013 draft"}]}}
---
