---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1883,"creation_ts":"2013-09-02 01:51:00 -0700","short_desc":"15.4.3.10: CreateOwnDataProperty no longer valid to use","delta_ts":"2013-09-27 14:47:05 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 17: August 23, 2013 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"andrebargull","name":"André Bargull"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":5295,"comment_count":0,"who":{"uid":"andrebargull","name":"André Bargull"},"bug_when":"2013-09-02 01:51:30 -0700","thetext":"CreateOwnDataProperty asserts when there is already an own property with the same property key. That means it's no longer safe to use CreateOwnDataProperty in 15.4.3.10 Array.prototype.slice at step 19.d.iii.\n\n\nThe following test case currently throws an assertion error:\n\n(new class extends Array{constructor(){this.push(0)}}).slice(0,1)"},{"commentid":5386,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-09-12 12:32:06 -0700","thetext":"Fixed in rev19 editor's draft\n\nRemoved the assert, CreateOwnDataProperty can now fail, but all uses already don't need (it can't fail) or already have the necessary checks."},{"commentid":5512,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-09-27 14:47:05 -0700","thetext":"fixed in rev19"}]}}
---
