---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":2096,"creation_ts":"2013-10-30 01:27:00 -0700","short_desc":"7.4.7.1 ListIterator next( ): Invalid assertion in step 2","delta_ts":"2013-11-08 13:09:30 -0800","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 20: October 28, 2013 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"enhancement","everconfirmed":true,"reporter":{"uid":"andrebargull","name":"André Bargull"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":6206,"comment_count":0,"who":{"uid":"andrebargull","name":"André Bargull"},"bug_when":"2013-10-30 01:27:50 -0700","thetext":"7.4.7.1 ListIterator next(), step 2:\n\nChange assertion to `throw TypeError`. \n\nThis is necessary because list iterators can escape to user code."},{"commentid":6337,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-11-01 12:43:02 -0700","thetext":"fixed in rev21 editor's draft"},{"commentid":6587,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-11-08 13:09:30 -0800","thetext":"fixed in rev21 draft"}]}}
---
