---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":3061,"creation_ts":"2014-07-24 18:02:00 -0700","short_desc":"19.1.2.1 Object.assign does not account for throwing undefined","delta_ts":"2014-07-25 06:18:54 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 26: July 18, 2014 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"INVALID","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"miloignis","name":"Nathan Braswell"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"cc":"claude.pache","long_desc":[{"commentid":9544,"comment_count":0,"who":{"uid":"miloignis","name":"Nathan Braswell"},"bug_when":"2014-07-24 18:02:32 -0700","thetext":"19.1.2.1 Object.assign ( target, ...source )\n\nIn step 5.i pendingException is set to be undefined.\nThis is then updated in 5.j.iv.1, 5.j.v.2.a, and 5.j.v.3.b.i.\nFinally, it is checked in 5.k to see if it is still undefined, and if it is, it is then re-thrown.\n\nHowever, I think it is possible to throw undefined, which would be lost and not registered under this scheme of checking if pendingException is undefined.\n\nSorry if I misunderstood something; thanks for your time!"},{"commentid":9555,"comment_count":1,"who":{"uid":"claude.pache","name":"Claude Pache"},"bug_when":"2014-07-25 06:18:54 -0700","thetext":"(In reply to Nathan Braswell from comment #0)\n\nIn steps 5.j.iv.1, 5.j.v.2.a, and 5.j.v.3.b.i, `pendingException` is updated to a Completion Record (see Section 6.2.2). For instance, if `undefined` is thrown, you don't get a bare `undefined`, but:\n\n    Completion{[[type]]: throw, [[value]]: undefined, [[target]]: empty}"}]}}
---
