<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] Problem catching exceptions in c# generated	code
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Problem%20catching%20exceptions%20in%20c%23%20generated%0A%09code&In-Reply-To=%3Cd50c5150802210850i69f9c3adi51577254f3f15df0%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="026671.html">
   <LINK REL="Next"  HREF="026674.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] Problem catching exceptions in c# generated	code</H1>
    <B>Ed Sykes</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Problem%20catching%20exceptions%20in%20c%23%20generated%0A%09code&In-Reply-To=%3Cd50c5150802210850i69f9c3adi51577254f3f15df0%40mail.gmail.com%3E"
       TITLE="[antlr-interest] Problem catching exceptions in c# generated	code">ed.sykes at gmail.com
       </A><BR>
    <I>Thu Feb 21 08:50:18 PST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="026671.html">[antlr-interest] Problem catching exceptions in c# generated code
</A></li>
        <LI>Next message: <A HREF="026674.html">[antlr-interest] $ in action  comments
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#26672">[ date ]</a>
              <a href="thread.html#26672">[ thread ]</a>
              <a href="subject.html#26672">[ subject ]</a>
              <a href="author.html#26672">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>You're right, i should have mentioned that the exception is being thrown
from the lexer, which is being called by the parser.

The try catch was around just the entry point on the parser, i've put the
try catch now around the whole setup / parse and still have the same
problem:

try
{
    MetricellKPIExpressionLexer lex = new MetricellKPIExpressionLexer(new
ANTLRStringStream(_expression));
    CommonTokenStream tokens = new CommonTokenStream(lex);
    MetricellKPIExpressionParser parser = new
MetricellKPIExpressionParser(tokens);

** MetricellKPIExpressionParser.expr_return result = parser.expr();
    CommonTree parsedTree = (CommonTree)(result.Tree);
    isValid = hasValidMeasures(parsedTree);
}
catch (MismatchedTokenException mmt)
{
    isValid = false;
}
catch (Exception ex)
{
    isValid = false;
}

In either case when the exception is thrown it should find the catch block
in the execution path. very puzzling. I've put the call stack below:

MetricellWebApplication.DLL!MetricellKPIExpressionLexer.mAND()
MetricellWebApplication.DLL!MetricellKPIExpressionLexer.mTokens()
[External Code]
MetricellWebApplication.DLL!MetricellKPIExpressionParser.expr()
MetricellWebApplication.DLL!MetriCell.MetricellKPIExpression.isValid()

At least i know that the exception can be caught from
MetricellKPIExpressionLexer.mAND() and that it can't be caught from
MetricellKPIExpression.isValid(). I can move the exception handling around
and see what the highest point in the call stack that works is. I suspect
that it's going to be
MetricellWebApplication.DLL!MetricellKPIExpressionLexer.mTokens(), but let's
see.

Not wanting to edit the generated code is exactly why i'm trying to fix
this!

thanks, ed

On Thu, Feb 21, 2008 at 3:16 PM, Johannes Luber &lt;<A HREF="http://www.antlr.org/mailman/listinfo/antlr-interest">jaluber at gmx.de</A>&gt; wrote:

&gt;<i> Ed Sykes schrieb:
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; I've just tried moving the try catch into the lexer around the call to
</I>&gt;<i> &gt; Antlr.Runtime.Match() and this seems to catch the exception. I'm
</I>&gt;<i> &gt; confused as to why putting the code in the driver doesn't work, but
</I>&gt;<i> &gt; moving the try catch to the lexer does.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; at least i have a workaround if i can't figure out how to get it working
</I>&gt;<i> &gt; in the driver.
</I>&gt;<i>
</I>&gt;<i> Now I believe I know what's your problem actually is. You are getting
</I>&gt;<i> exceptions in the lexer, but you aren't catching them because the catch
</I>&gt;<i> clause doesn't include the lexer. That would make sense as the lexing is
</I>&gt;<i> done separately from the parsing. There only one problem with the
</I>&gt;<i> theory: FillBuffer() is called by NextToken() is called by the parser.
</I>&gt;<i> So the exception should be on the call chain. Strange. Nonetheless test
</I>&gt;<i> it, because changing the generate code is always a bad idea, if there is
</I>&gt;<i> an other way.
</I>&gt;<i>
</I>&gt;<i> And to your other question in the other email: ANTLR has a special
</I>&gt;<i> syntax for exceptions in its grammar, but that doesn't work yet.
</I>&gt;<i>
</I>&gt;<i> Johannes
</I>&gt;<i>
</I>-------------- next part --------------
An HTML attachment was scrubbed...
URL: <A HREF="http://www.antlr.org/pipermail/antlr-interest/attachments/20080221/f85e67e7/attachment.html">http://www.antlr.org/pipermail/antlr-interest/attachments/20080221/f85e67e7/attachment.html</A> 
</PRE>






<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="026671.html">[antlr-interest] Problem catching exceptions in c# generated code
</A></li>
	<LI>Next message: <A HREF="026674.html">[antlr-interest] $ in action  comments
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#26672">[ date ]</a>
              <a href="thread.html#26672">[ thread ]</a>
              <a href="subject.html#26672">[ subject ]</a>
              <a href="author.html#26672">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
