<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.ecmascript.org/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.4+"
          urlbase="https://bugs.ecmascript.org/"
          
          maintainer="dherman@mozilla.com"
>

    <bug>
          <bug_id>1361</bug_id>
          
          <creation_ts>2013-03-20 10:43:00 -0700</creation_ts>
          <short_desc>5.2: obsolete definition of &quot;throw an exception&quot;</short_desc>
          <delta_ts>2013-05-14 18:13:31 -0700</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>Draft for 6th Edition</product>
          <component>editorial issue</component>
          <version>Rev 14: March 8, 2013 Draft</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>Normal</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Michael Dyck">jmdyck</reporter>
          <assigned_to name="Allen Wirfs-Brock">allen</assigned_to>
          
          

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>3508</commentid>
    <comment_count>0</comment_count>
    <who name="Michael Dyck">jmdyck</who>
    <bug_when>2013-03-20 10:43:52 -0700</bug_when>
    <thetext>In 5.2 &quot;Algorithm Conventions&quot;,
the last paragraph says:
    If an algorithm is defined to “throw an exception”, execution of the
    algorithm is terminated and no result is returned. The calling algorithms
    are also terminated, until an algorithm step is reached that explicitly
    deals with the exception, using terminology such as “If an exception was
    thrown…”. Once such an algorithm step has been encountered the exception
    is no longer considered to have occurred.

This is no longer true, and has been superseded by 8.2.3.3 and 8.2.3.4.

Delete the paragraph.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>3753</commentid>
    <comment_count>1</comment_count>
    <who name="Allen Wirfs-Brock">allen</who>
    <bug_when>2013-05-12 13:58:45 -0700</bug_when>
    <thetext>fixed in rev15 editor&apos;s draft.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>3917</commentid>
    <comment_count>2</comment_count>
    <who name="Allen Wirfs-Brock">allen</who>
    <bug_when>2013-05-14 18:13:31 -0700</bug_when>
    <thetext>resolved in rev 15, May 14, 2013 draft</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>